// Copyright (c) Chris Pulman. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis.CSharp;

namespace MitsubishiRx;

internal static class MitsubishiTagClientEmitter
{
    public static string Emit(MitsubishiTagClientGenerator.SchemaModel model)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine("using System.Linq;");
        builder.AppendLine("using System.Reactive.Linq;");
        builder.AppendLine("using System.Threading;");
        builder.AppendLine("using System.Threading.Tasks;");
        builder.AppendLine();
        builder.AppendLine("namespace MitsubishiRx;");
        builder.AppendLine();
        builder.AppendLine("public static class GeneratedMitsubishiTagClientExtensions");
        builder.AppendLine("{");
        builder.AppendLine("    public static GeneratedMitsubishiTagClient Generated(this global::MitsubishiRx.MitsubishiRx owner) => new(owner);");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("public sealed partial class GeneratedMitsubishiTagClient");
        builder.AppendLine("{");
        builder.AppendLine("    private readonly global::MitsubishiRx.MitsubishiRx _owner;");
        builder.AppendLine();
        builder.AppendLine("    public GeneratedMitsubishiTagClient(global::MitsubishiRx.MitsubishiRx owner)");
        builder.AppendLine("    {");
        builder.AppendLine("        _owner = owner ?? throw new ArgumentNullException(nameof(owner));");
        builder.AppendLine("        Tags = new TagsClient(owner);");
        builder.AppendLine("        Groups = new GroupsClient(owner);");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public TagsClient Tags { get; }");
        builder.AppendLine();
        builder.AppendLine("    public GroupsClient Groups { get; }");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("public sealed class TagsClient");
        builder.AppendLine("{");
        builder.AppendLine("    private readonly global::MitsubishiRx.MitsubishiRx _owner;");
        builder.AppendLine("    public TagsClient(global::MitsubishiRx.MitsubishiRx owner) => _owner = owner;");

        foreach (var tag in model.Tags)
        {
            string propertyName = SanitizeIdentifier(tag.Name);
            string nestedType = propertyName + "Tag";
            builder.AppendLine($"    public {nestedType} {propertyName} => new(_owner);");
        }

        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("public sealed class GroupsClient");
        builder.AppendLine("{");
        builder.AppendLine("    private readonly global::MitsubishiRx.MitsubishiRx _owner;");
        builder.AppendLine("    public GroupsClient(global::MitsubishiRx.MitsubishiRx owner) => _owner = owner;");
        foreach (var group in model.Groups)
        {
            string propertyName = SanitizeIdentifier(group.Name);
            string nestedType = propertyName + "Group";
            builder.AppendLine($"    public {nestedType} {propertyName} => new(_owner);");
        }
        builder.AppendLine("}");
        builder.AppendLine();

        foreach (var tag in model.Tags)
        {
            AppendTagType(builder, tag.Name, tag.DataType);
        }

        foreach (var group in model.Groups)
        {
            AppendGroupSnapshotType(builder, group, model.Tags);
            AppendGroupType(builder, group, model.Tags);
        }

        return builder.ToString();
    }

    private static void AppendTagType(StringBuilder builder, string tagName, string? dataType)
    {
        string propertyName = SanitizeIdentifier(tagName);
        string nestedType = propertyName + "Tag";
        string escapedTagName = tagName.Replace("\"", "\\\"");
        string readType = ResolveReadType(dataType);
        string readMethod = ResolveReadMethod(dataType);
        string writeType = ResolveWriteType(dataType);
        string writeMethod = ResolveWriteMethod(dataType);

        builder.AppendLine($"public sealed class {nestedType}");
        builder.AppendLine("{");
        builder.AppendLine("    private readonly global::MitsubishiRx.MitsubishiRx _owner;");
        builder.AppendLine($"    public {nestedType}(global::MitsubishiRx.MitsubishiRx owner) => _owner = owner;");
        builder.AppendLine($"    public Task<Responce<{readType}>> ReadAsync(CancellationToken cancellationToken = default) => _owner.{readMethod}(\"{escapedTagName}\", cancellationToken);");
        builder.AppendLine($"    public Task<Responce> WriteAsync({writeType} value, CancellationToken cancellationToken = default) => _owner.{writeMethod}(\"{escapedTagName}\", value, cancellationToken);");
        builder.AppendLine($"    public IObservable<MitsubishiReactiveValue<{readType}>> Observe(TimeSpan pollInterval, TimeSpan? minimumUpdateSpacing = null) => _owner.ObserveReactiveTag<{readType}>(\"{escapedTagName}\", pollInterval, minimumUpdateSpacing);");
        builder.AppendLine("}");
        builder.AppendLine();
    }

    private static void AppendGroupType(StringBuilder builder, MitsubishiTagClientGenerator.GroupModel group, IReadOnlyList<MitsubishiTagClientGenerator.TagModel> tags)
    {
        string groupName = group.Name;
        string propertyName = SanitizeIdentifier(groupName);
        string nestedType = propertyName + "Group";
        string snapshotType = propertyName + "Snapshot";
        string escapedGroupName = groupName.Replace("\"", "\\\"");

        builder.AppendLine($"public sealed class {nestedType}");
        builder.AppendLine("{");
        builder.AppendLine("    private readonly global::MitsubishiRx.MitsubishiRx _owner;");
        builder.AppendLine($"    public {nestedType}(global::MitsubishiRx.MitsubishiRx owner) => _owner = owner;");
        builder.AppendLine($"    public async Task<Responce<{snapshotType}>> ReadAsync(CancellationToken cancellationToken = default)");
        builder.AppendLine("    {");
        builder.AppendLine($"        var result = await _owner.ReadTagGroupSnapshotAsync(\"{escapedGroupName}\", cancellationToken).ConfigureAwait(false);");
        builder.AppendLine("        if (!result.IsSucceed || result.Value is null)");
        builder.AppendLine("        {");
        builder.AppendLine($"            return new Responce<{snapshotType}>(result);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine($"        return new Responce<{snapshotType}>(result, {snapshotType}.FromSnapshot(result.Value));");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine($"    public async Task<Responce<{snapshotType}?>> ReadOptionalAsync(CancellationToken cancellationToken = default)");
        builder.AppendLine("    {");
        builder.AppendLine($"        var result = await _owner.ReadTagGroupSnapshotAsync(\"{escapedGroupName}\", cancellationToken).ConfigureAwait(false);");
        builder.AppendLine("        if (!result.IsSucceed || result.Value is null)");
        builder.AppendLine("        {");
        builder.AppendLine($"            return new Responce<{snapshotType}?>(result);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine($"        return new Responce<{snapshotType}?>(result, {snapshotType}.TryFromSnapshot(result.Value));");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine($"    public Task<Responce> WriteAsync({snapshotType} value, CancellationToken cancellationToken = default) => _owner.WriteTagGroupSnapshotAsync(value.ToSnapshot(), cancellationToken);");
        builder.AppendLine();
        builder.AppendLine($"    public IObservable<MitsubishiReactiveValue<{snapshotType}>> Observe(TimeSpan pollInterval, TimeSpan? minimumUpdateSpacing = null)");
        builder.AppendLine($"        => _owner.ObserveReactiveTagGroup(\"{escapedGroupName}\", pollInterval, minimumUpdateSpacing)");
        builder.AppendLine($"            .Select(static value => {snapshotType}.MapReactive(value));");
        builder.AppendLine();
        builder.AppendLine($"    public IObservable<MitsubishiReactiveValue<{snapshotType}?>> ObserveOptional(TimeSpan pollInterval, TimeSpan? minimumUpdateSpacing = null)");
        builder.AppendLine($"        => _owner.ObserveReactiveTagGroup(\"{escapedGroupName}\", pollInterval, minimumUpdateSpacing)");
        builder.AppendLine($"            .Select(static value => {snapshotType}.MapReactiveOptional(value));");
        builder.AppendLine("}");
        builder.AppendLine();
    }

    private static void AppendGroupSnapshotType(StringBuilder builder, MitsubishiTagClientGenerator.GroupModel group, IReadOnlyList<MitsubishiTagClientGenerator.TagModel> tags)
    {
        string snapshotType = SanitizeIdentifier(group.Name) + "Snapshot";
        string escapedGroupName = group.Name.Replace("\"", "\\\"");
        var orderedTags = group.TagNames
            .Select(name => tags.FirstOrDefault(tag => string.Equals(tag.Name, name, StringComparison.Ordinal)))
            .Where(static tag => tag is not null)
            .Cast<MitsubishiTagClientGenerator.TagModel>()
            .ToList();

        string constructorParameters = string.Join(", ", orderedTags.Select(static tag => $"{ResolveReadType(tag.DataType)} {SanitizeIdentifier(tag.Name)}"));

        builder.AppendLine($"public sealed partial record {snapshotType}({constructorParameters})");
        builder.AppendLine("{");
        builder.AppendLine($"    public static {snapshotType} FromSnapshot(MitsubishiTagGroupSnapshot snapshot)");
        builder.AppendLine("    {");
        builder.AppendLine("        ArgumentNullException.ThrowIfNull(snapshot);");
        builder.AppendLine($"        return new {snapshotType}(");
        for (int i = 0; i < orderedTags.Count; i++)
        {
            var tag = orderedTags[i];
            string suffix = i == orderedTags.Count - 1 ? string.Empty : ",";
            builder.AppendLine($"            snapshot.GetRequired<{ResolveReadType(tag.DataType)}>(\"{tag.Name.Replace("\"", "\\\"")}\"){suffix}");
        }

        builder.AppendLine("        );");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine($"    public static {snapshotType}? TryFromSnapshot(MitsubishiTagGroupSnapshot? snapshot)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (snapshot is null)");
        builder.AppendLine("        {");
        builder.AppendLine("            return default;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        try");
        builder.AppendLine("        {");
        builder.AppendLine($"            return new {snapshotType}(");
        for (int i = 0; i < orderedTags.Count; i++)
        {
            var tag = orderedTags[i];
            string suffix = i == orderedTags.Count - 1 ? string.Empty : ",";
            builder.AppendLine($"                snapshot.GetRequired<{ResolveReadType(tag.DataType)}>(\"{tag.Name.Replace("\"", "\\\"")}\"){suffix}");
        }
        builder.AppendLine("            );");
        builder.AppendLine("        }");
        builder.AppendLine("        catch (KeyNotFoundException)");
        builder.AppendLine("        {");
        builder.AppendLine("            return default;");
        builder.AppendLine("        }");
        builder.AppendLine("        catch (InvalidCastException)");
        builder.AppendLine("        {");
        builder.AppendLine("            return default;");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public MitsubishiTagGroupSnapshot ToSnapshot()");
        builder.AppendLine("    {");
        builder.AppendLine("        return new MitsubishiTagGroupSnapshot(");
        builder.AppendLine($"            \"{escapedGroupName}\",");
        builder.AppendLine("            new Dictionary<string, object?>(StringComparer.OrdinalIgnoreCase)");
        builder.AppendLine("            {");
        for (int i = 0; i < orderedTags.Count; i++)
        {
            var tag = orderedTags[i];
            string suffix = i == orderedTags.Count - 1 ? string.Empty : ",";
            builder.AppendLine($"                [\"{tag.Name.Replace("\"", "\\\"")}\"] = {SanitizeIdentifier(tag.Name)}{suffix}");
        }
        builder.AppendLine("            });");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine($"    public static MitsubishiReactiveValue<{snapshotType}> MapReactive(MitsubishiReactiveValue<MitsubishiTagGroupSnapshot> value)");
        builder.AppendLine("    {");
        builder.AppendLine("        ArgumentNullException.ThrowIfNull(value);");
        builder.AppendLine("        if (value.Value is null)");
        builder.AppendLine("        {");
        builder.AppendLine($"            return new MitsubishiReactiveValue<{snapshotType}>(default, value.TimestampUtc, value.Quality, value.IsHeartbeat, value.IsStale, value.Source, value.Error, value.ErrorCode, value.Exception);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        try");
        builder.AppendLine("        {");
        builder.AppendLine($"            return new MitsubishiReactiveValue<{snapshotType}>(FromSnapshot(value.Value), value.TimestampUtc, value.Quality, value.IsHeartbeat, value.IsStale, value.Source, value.Error, value.ErrorCode, value.Exception);");
        builder.AppendLine("        }");
        builder.AppendLine("        catch (Exception ex)");
        builder.AppendLine("        {");
        builder.AppendLine($"            return new MitsubishiReactiveValue<{snapshotType}>(default, value.TimestampUtc, MitsubishiReactiveQuality.Error, Source: value.Source, Error: ex.Message, ErrorCode: value.ErrorCode, Exception: ex);");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine($"    public static MitsubishiReactiveValue<{snapshotType}?> MapReactiveOptional(MitsubishiReactiveValue<MitsubishiTagGroupSnapshot> value)");
        builder.AppendLine("    {");
        builder.AppendLine("        ArgumentNullException.ThrowIfNull(value);");
        builder.AppendLine($"        return new MitsubishiReactiveValue<{snapshotType}?>(TryFromSnapshot(value.Value), value.TimestampUtc, value.Quality, value.IsHeartbeat, value.IsStale, value.Source, value.Error, value.ErrorCode, value.Exception);");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        builder.AppendLine();
    }

    private static string ResolveReadType(string? dataType)
        => dataType switch
        {
            "Bit" => "bool",
            "String" => "string",
            "Float" => "float",
            "DWord" or "UInt32" => "uint",
            "Int32" => "int",
            "Int16" => "short",
            "UInt16" or "Word" or null => "ushort",
            _ => "ushort",
        };

    private static string ResolveReadMethod(string? dataType)
        => dataType switch
        {
            "Bit" => "ReadGeneratedBitTagAsync",
            "String" => "ReadStringByTagAsync",
            "Float" => "ReadFloatByTagAsync",
            "DWord" or "UInt32" => "ReadDWordByTagAsync",
            "Int32" => "ReadInt32ByTagAsync",
            "Int16" => "ReadInt16ByTagAsync",
            "UInt16" or "Word" or null => "ReadUInt16ByTagAsync",
            _ => "ReadUInt16ByTagAsync",
        };

    private static string ResolveWriteType(string? dataType) => ResolveReadType(dataType);

    private static string ResolveWriteMethod(string? dataType)
        => dataType switch
        {
            "Bit" => "WriteGeneratedBitTagAsync",
            "String" => "WriteStringByTagAsync",
            "Float" => "WriteFloatByTagAsync",
            "DWord" or "UInt32" => "WriteDWordByTagAsync",
            "Int32" => "WriteInt32ByTagAsync",
            "Int16" => "WriteInt16ByTagAsync",
            "UInt16" or "Word" or null => "WriteUInt16ByTagAsync",
            _ => "WriteUInt16ByTagAsync",
        };

    private static string SanitizeIdentifier(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return "Tag";
        }

        var builder = new StringBuilder();
        bool capitalize = true;
        foreach (char ch in value)
        {
            if (char.IsLetterOrDigit(ch))
            {
                builder.Append(capitalize ? char.ToUpperInvariant(ch) : ch);
                capitalize = false;
            }
            else
            {
                capitalize = true;
            }
        }

        if (builder.Length == 0)
        {
            builder.Append("Tag");
        }

        if (!char.IsLetter(builder[0]) && builder[0] != '_')
        {
            builder.Insert(0, '_');
        }

        return builder.ToString();
    }
}
