// Copyright (c) 2022-2026 Chris Pulman. All rights reserved.
// Chris Pulman licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace MitsubishiRx;

/// <summary>Emits strongly typed Mitsubishi tag client source.</summary>
internal static class MitsubishiTagClientEmitter
{
    /// <summary>Emits generated client source for the supplied schema model.</summary>
    /// <param name="model">Parsed schema model.</param>
    /// <returns>Generated client source.</returns>
    public static string Emit(MitsubishiTagClientGenerator.SchemaModel model)
    {
        var builder = new StringBuilder();
        AppendLine(builder, "// <auto-generated />");
        AppendLine(builder, "using System;");
        AppendLine(builder, "using System.Collections.Generic;");
        AppendLine(builder, "using System.Linq;");
        AppendLine(builder, "using System.Threading;");
        AppendLine(builder, "using System.Threading.Tasks;");
        AppendLine(builder, "using ReactiveUI.Primitives;");
        AppendLine(builder);
        AppendLine(builder, "namespace MitsubishiRx;");
        AppendLine(builder);
        AppendLine(builder, "public static class GeneratedMitsubishiTagClientExtensions");
        AppendLine(builder, "{");
        AppendLine(builder, "    public static GeneratedMitsubishiTagClient Generated(this global::MitsubishiRx.MitsubishiRx owner) => new(owner);");
        AppendLine(builder, "}");
        AppendLine(builder);
        AppendLine(builder, "public sealed partial class GeneratedMitsubishiTagClient");
        AppendLine(builder, "{");
        AppendLine(builder, "    private readonly global::MitsubishiRx.MitsubishiRx _owner;");
        AppendLine(builder);
        AppendLine(builder, "    public GeneratedMitsubishiTagClient(global::MitsubishiRx.MitsubishiRx owner)");
        AppendLine(builder, "    {");
        AppendLine(builder, "        _owner = owner ?? throw new ArgumentNullException(nameof(owner));");
        AppendLine(builder, "        Tags = new TagsClient(owner);");
        AppendLine(builder, "        Groups = new GroupsClient(owner);");
        AppendLine(builder, "    }");
        AppendLine(builder);
        AppendLine(builder, "    public TagsClient Tags { get; }");
        AppendLine(builder);
        AppendLine(builder, "    public GroupsClient Groups { get; }");
        AppendLine(builder, "}");
        AppendLine(builder);
        AppendLine(builder, "public sealed class TagsClient");
        AppendLine(builder, "{");
        AppendLine(builder, "    private readonly global::MitsubishiRx.MitsubishiRx _owner;");
        AppendLine(builder, "    public TagsClient(global::MitsubishiRx.MitsubishiRx owner) => _owner = owner;");

        foreach (var tag in model.Tags)
        {
            string propertyName = SanitizeIdentifier(tag.Name);
            string nestedType = propertyName + "Tag";
            AppendLine(builder, $"    public {nestedType} {propertyName} => new(_owner);");
        }

        AppendLine(builder, "}");
        AppendLine(builder);
        AppendLine(builder, "public sealed class GroupsClient");
        AppendLine(builder, "{");
        AppendLine(builder, "    private readonly global::MitsubishiRx.MitsubishiRx _owner;");
        AppendLine(builder, "    public GroupsClient(global::MitsubishiRx.MitsubishiRx owner) => _owner = owner;");
        foreach (var group in model.Groups)
        {
            string propertyName = SanitizeIdentifier(group.Name);
            string nestedType = propertyName + "Group";
            AppendLine(builder, $"    public {nestedType} {propertyName} => new(_owner);");
        }

        AppendLine(builder, "}");
        AppendLine(builder);

        foreach (var tag in model.Tags)
        {
            AppendTagType(builder, tag.Name, tag.DataType);
        }

        foreach (var group in model.Groups)
        {
            AppendGroupSnapshotType(builder, group, model.Tags);
            AppendGroupType(builder, group, model.Tags);
        }

        return builder.ToString();
    }

    /// <summary>Converts a schema name into a valid C# identifier.</summary>
    /// <param name="value">Schema name.</param>
    /// <returns>A valid C# identifier.</returns>
    internal static string SanitizeIdentifier(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return "Tag";
        }

        var builder = new StringBuilder();
        bool capitalize = true;
        foreach (char ch in value)
        {
            if (char.IsLetterOrDigit(ch))
            {
                _ = builder.Append(capitalize ? char.ToUpperInvariant(ch) : ch);
                capitalize = false;
            }
            else
            {
                capitalize = true;
            }
        }

        if (builder.Length == 0)
        {
            _ = builder.Append("Tag");
        }

        if (!char.IsLetter(builder[0]) && builder[0] != '_')
        {
            _ = builder.Insert(0, '_');
        }

        return builder.ToString();
    }

    /// <summary>Appends a generated tag client type.</summary>
    /// <param name="builder">Source builder.</param>
    /// <param name="tagName">Schema tag name.</param>
    /// <param name="dataType">Schema data type.</param>
    private static void AppendTagType(StringBuilder builder, string tagName, string? dataType)
    {
        string propertyName = SanitizeIdentifier(tagName);
        string nestedType = propertyName + "Tag";
        string escapedTagName = tagName.Replace("\"", "\\\"");
        string readType = ResolveReadType(dataType);
        string readMethod = ResolveReadMethod(dataType);
        string writeType = ResolveWriteType(dataType);
        string writeMethod = ResolveWriteMethod(dataType);

        AppendLine(builder, $"public sealed class {nestedType}");
        AppendLine(builder, "{");
        AppendLine(builder, "    private readonly global::MitsubishiRx.MitsubishiRx _owner;");
        AppendLine(builder, $"    public {nestedType}(global::MitsubishiRx.MitsubishiRx owner) => _owner = owner;");
        AppendLine(builder, $"    public Task<Responce<{readType}>> ReadAsync(CancellationToken cancellationToken = default) => _owner.{readMethod}(\"{escapedTagName}\", cancellationToken);");
        AppendLine(builder, $"    public Task<Responce> WriteAsync({writeType} value, CancellationToken cancellationToken = default) => _owner.{writeMethod}(\"{escapedTagName}\", value, cancellationToken);");
        AppendLine(builder, $"    public IObservable<MitsubishiReactiveValue<{readType}>> Observe(TimeSpan pollInterval, TimeSpan? minimumUpdateSpacing = null) => _owner.ObserveReactiveTag<{readType}>(\"{escapedTagName}\", pollInterval, minimumUpdateSpacing);");
        AppendLine(builder, "}");
        AppendLine(builder);
    }

    /// <summary>Appends a generated group client type.</summary>
    /// <param name="builder">Source builder.</param>
    /// <param name="group">Schema group.</param>
    /// <param name="tags">All schema tags.</param>
    private static void AppendGroupType(StringBuilder builder, MitsubishiTagClientGenerator.GroupModel group, IReadOnlyList<MitsubishiTagClientGenerator.TagModel> tags)
    {
        string groupName = group.Name;
        string propertyName = SanitizeIdentifier(groupName);
        string nestedType = propertyName + "Group";
        string snapshotType = propertyName + "Snapshot";
        string escapedGroupName = groupName.Replace("\"", "\\\"");

        AppendLine(builder, $"public sealed class {nestedType}");
        AppendLine(builder, "{");
        AppendLine(builder, "    private readonly global::MitsubishiRx.MitsubishiRx _owner;");
        AppendLine(builder, $"    public {nestedType}(global::MitsubishiRx.MitsubishiRx owner) => _owner = owner;");
        AppendLine(builder, $"    public async Task<Responce<{snapshotType}>> ReadAsync(CancellationToken cancellationToken = default)");
        AppendLine(builder, "    {");
        AppendLine(builder, $"        var result = await _owner.ReadTagGroupSnapshotAsync(\"{escapedGroupName}\", cancellationToken).ConfigureAwait(false);");
        AppendLine(builder, "        if (!result.IsSucceed || result.Value is null)");
        AppendLine(builder, "        {");
        AppendLine(builder, $"            return new Responce<{snapshotType}>(result);");
        AppendLine(builder, "        }");
        AppendLine(builder);
        AppendLine(builder, $"        return new Responce<{snapshotType}>(result, {snapshotType}.FromSnapshot(result.Value));");
        AppendLine(builder, "    }");
        AppendLine(builder);
        AppendLine(builder, $"    public async Task<Responce<{snapshotType}?>> ReadOptionalAsync(CancellationToken cancellationToken = default)");
        AppendLine(builder, "    {");
        AppendLine(builder, $"        var result = await _owner.ReadTagGroupSnapshotAsync(\"{escapedGroupName}\", cancellationToken).ConfigureAwait(false);");
        AppendLine(builder, "        if (!result.IsSucceed || result.Value is null)");
        AppendLine(builder, "        {");
        AppendLine(builder, $"            return new Responce<{snapshotType}?>(result);");
        AppendLine(builder, "        }");
        AppendLine(builder);
        AppendLine(builder, $"        return new Responce<{snapshotType}?>(result, {snapshotType}.TryFromSnapshot(result.Value));");
        AppendLine(builder, "    }");
        AppendLine(builder);
        AppendLine(builder, $"    public Task<Responce> WriteAsync({snapshotType} value, CancellationToken cancellationToken = default) => _owner.WriteTagGroupSnapshotAsync(value.ToSnapshot(), cancellationToken);");
        AppendLine(builder);
        AppendLine(builder, $"    public IObservable<MitsubishiReactiveValue<{snapshotType}>> Observe(TimeSpan pollInterval, TimeSpan? minimumUpdateSpacing = null)");
        AppendLine(builder, $"        => _owner.ObserveReactiveTagGroup(\"{escapedGroupName}\", pollInterval, minimumUpdateSpacing)");
        AppendLine(builder, $"            .Select(static value => {snapshotType}.MapReactive(value));");
        AppendLine(builder);
        AppendLine(builder, $"    public IObservable<MitsubishiReactiveValue<{snapshotType}?>> ObserveOptional(TimeSpan pollInterval, TimeSpan? minimumUpdateSpacing = null)");
        AppendLine(builder, $"        => _owner.ObserveReactiveTagGroup(\"{escapedGroupName}\", pollInterval, minimumUpdateSpacing)");
        AppendLine(builder, $"            .Select(static value => {snapshotType}.MapReactiveOptional(value));");
        AppendLine(builder, "}");
        AppendLine(builder);
    }

    /// <summary>Appends a generated group snapshot type.</summary>
    /// <param name="builder">Source builder.</param>
    /// <param name="group">Schema group.</param>
    /// <param name="tags">All schema tags.</param>
    private static void AppendGroupSnapshotType(StringBuilder builder, MitsubishiTagClientGenerator.GroupModel group, IReadOnlyList<MitsubishiTagClientGenerator.TagModel> tags)
    {
        string snapshotType = SanitizeIdentifier(group.Name) + "Snapshot";
        string escapedGroupName = group.Name.Replace("\"", "\\\"");
        var orderedTags = group.TagNames
            .Select(name => tags.FirstOrDefault(tag => string.Equals(tag.Name, name, StringComparison.Ordinal)))
            .Where(static tag => tag is not null)
            .Cast<MitsubishiTagClientGenerator.TagModel>()
            .ToList();

        string constructorParameters = string.Join(", ", orderedTags.Select(static tag => $"{ResolveReadType(tag.DataType)} {SanitizeIdentifier(tag.Name)}"));

        AppendLine(builder, $"public sealed partial record {snapshotType}({constructorParameters})");
        AppendLine(builder, "{");
        AppendLine(builder, $"    public static {snapshotType} FromSnapshot(MitsubishiTagGroupSnapshot snapshot)");
        AppendLine(builder, "    {");
        AppendLine(builder, "        ArgumentNullException.ThrowIfNull(snapshot);");
        AppendLine(builder, $"        return new {snapshotType}(");
        for (int i = 0; i < orderedTags.Count; i++)
        {
            var tag = orderedTags[i];
            string suffix = i == orderedTags.Count - 1 ? string.Empty : ",";
            AppendLine(builder, $"            snapshot.GetRequired<{ResolveReadType(tag.DataType)}>(\"{tag.Name.Replace("\"", "\\\"")}\"){suffix}");
        }

        AppendLine(builder, "        );");
        AppendLine(builder, "    }");
        AppendLine(builder);
        AppendLine(builder, $"    public static {snapshotType}? TryFromSnapshot(MitsubishiTagGroupSnapshot? snapshot)");
        AppendLine(builder, "    {");
        AppendLine(builder, "        if (snapshot is null)");
        AppendLine(builder, "        {");
        AppendLine(builder, "            return default;");
        AppendLine(builder, "        }");
        AppendLine(builder);
        AppendLine(builder, "        try");
        AppendLine(builder, "        {");
        AppendLine(builder, $"            return new {snapshotType}(");
        for (int i = 0; i < orderedTags.Count; i++)
        {
            var tag = orderedTags[i];
            string suffix = i == orderedTags.Count - 1 ? string.Empty : ",";
            AppendLine(builder, $"                snapshot.GetRequired<{ResolveReadType(tag.DataType)}>(\"{tag.Name.Replace("\"", "\\\"")}\"){suffix}");
        }

        AppendLine(builder, "            );");
        AppendLine(builder, "        }");
        AppendLine(builder, "        catch (KeyNotFoundException)");
        AppendLine(builder, "        {");
        AppendLine(builder, "            return default;");
        AppendLine(builder, "        }");
        AppendLine(builder, "        catch (InvalidCastException)");
        AppendLine(builder, "        {");
        AppendLine(builder, "            return default;");
        AppendLine(builder, "        }");
        AppendLine(builder, "    }");
        AppendLine(builder);
        AppendLine(builder, "    public MitsubishiTagGroupSnapshot ToSnapshot()");
        AppendLine(builder, "    {");
        AppendLine(builder, "        return new MitsubishiTagGroupSnapshot(");
        AppendLine(builder, $"            \"{escapedGroupName}\",");
        AppendLine(builder, "            new Dictionary<string, object?>(StringComparer.OrdinalIgnoreCase)");
        AppendLine(builder, "            {");
        for (int i = 0; i < orderedTags.Count; i++)
        {
            var tag = orderedTags[i];
            string suffix = i == orderedTags.Count - 1 ? string.Empty : ",";
            AppendLine(builder, $"                [\"{tag.Name.Replace("\"", "\\\"")}\"] = {SanitizeIdentifier(tag.Name)}{suffix}");
        }

        AppendLine(builder, "            });");
        AppendLine(builder, "    }");
        AppendLine(builder);
        AppendLine(builder, $"    public static MitsubishiReactiveValue<{snapshotType}> MapReactive(MitsubishiReactiveValue<MitsubishiTagGroupSnapshot> value)");
        AppendLine(builder, "    {");
        AppendLine(builder, "        ArgumentNullException.ThrowIfNull(value);");
        AppendLine(builder, "        if (value.Value is null)");
        AppendLine(builder, "        {");
        AppendLine(builder, $"            return new MitsubishiReactiveValue<{snapshotType}>(default, value.TimestampUtc, value.Quality, value.IsHeartbeat, value.IsStale, value.Source, value.Error, value.ErrorCode, value.Exception);");
        AppendLine(builder, "        }");
        AppendLine(builder);
        AppendLine(builder, "        try");
        AppendLine(builder, "        {");
        AppendLine(builder, $"            return new MitsubishiReactiveValue<{snapshotType}>(FromSnapshot(value.Value), value.TimestampUtc, value.Quality, value.IsHeartbeat, value.IsStale, value.Source, value.Error, value.ErrorCode, value.Exception);");
        AppendLine(builder, "        }");
        AppendLine(builder, "        catch (Exception ex)");
        AppendLine(builder, "        {");
        AppendLine(builder, $"            return new MitsubishiReactiveValue<{snapshotType}>(default, value.TimestampUtc, MitsubishiReactiveQuality.Error, Source: value.Source, Error: ex.Message, ErrorCode: value.ErrorCode, Exception: ex);");
        AppendLine(builder, "        }");
        AppendLine(builder, "    }");
        AppendLine(builder);
        AppendLine(builder, $"    public static MitsubishiReactiveValue<{snapshotType}?> MapReactiveOptional(MitsubishiReactiveValue<MitsubishiTagGroupSnapshot> value)");
        AppendLine(builder, "    {");
        AppendLine(builder, "        ArgumentNullException.ThrowIfNull(value);");
        AppendLine(builder, $"        return new MitsubishiReactiveValue<{snapshotType}?>(TryFromSnapshot(value.Value), value.TimestampUtc, value.Quality, value.IsHeartbeat, value.IsStale, value.Source, value.Error, value.ErrorCode, value.Exception);");
        AppendLine(builder, "    }");
        AppendLine(builder, "}");
        AppendLine(builder);
    }

    /// <summary>Resolves the generated read value type.</summary>
    /// <param name="dataType">Schema data type.</param>
    /// <returns>Generated read value type.</returns>
    private static string ResolveReadType(string? dataType)
        => dataType switch
        {
            "Bit" => "bool",
            "String" => "string",
            "Float" => "float",
            "DWord" or "UInt32" => "uint",
            "Int32" => "int",
            "Int16" => "short",
            "UInt16" or "Word" or null => "ushort",
            _ => "ushort",
        };

    /// <summary>Resolves the generated read method name.</summary>
    /// <param name="dataType">Schema data type.</param>
    /// <returns>Generated read method name.</returns>
    private static string ResolveReadMethod(string? dataType)
        => dataType switch
        {
            "Bit" => "ReadGeneratedBitTagAsync",
            "String" => "ReadStringByTagAsync",
            "Float" => "ReadFloatByTagAsync",
            "DWord" or "UInt32" => "ReadDWordByTagAsync",
            "Int32" => "ReadInt32ByTagAsync",
            "Int16" => "ReadInt16ByTagAsync",
            "UInt16" or "Word" or null => "ReadUInt16ByTagAsync",
            _ => "ReadUInt16ByTagAsync",
        };

    /// <summary>Resolves the generated write value type.</summary>
    /// <param name="dataType">Schema data type.</param>
    /// <returns>Generated write value type.</returns>
    private static string ResolveWriteType(string? dataType) => ResolveReadType(dataType);

    /// <summary>Resolves the generated write method name.</summary>
    /// <param name="dataType">Schema data type.</param>
    /// <returns>Generated write method name.</returns>
    private static string ResolveWriteMethod(string? dataType)
        => dataType switch
        {
            "Bit" => "WriteGeneratedBitTagAsync",
            "String" => "WriteStringByTagAsync",
            "Float" => "WriteFloatByTagAsync",
            "DWord" or "UInt32" => "WriteDWordByTagAsync",
            "Int32" => "WriteInt32ByTagAsync",
            "Int16" => "WriteInt16ByTagAsync",
            "UInt16" or "Word" or null => "WriteUInt16ByTagAsync",
            _ => "WriteUInt16ByTagAsync",
        };

    /// <summary>Appends an empty generated source line.</summary>
    /// <param name="builder">Source builder.</param>
    private static void AppendLine(StringBuilder builder) => _ = builder.AppendLine();

    /// <summary>Appends a generated source line.</summary>
    /// <param name="builder">Source builder.</param>
    /// <param name="value">Source line.</param>
    private static void AppendLine(StringBuilder builder, string value) => _ = builder.AppendLine(value);
}
