// Copyright (c) 2022-2026 Chris Pulman. All rights reserved.
// Chris Pulman licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MitsubishiRx;

/// <summary>Generates strongly typed Mitsubishi tag clients from embedded tag schema JSON.</summary>
[Generator]
public sealed class MitsubishiTagClientGenerator : IIncrementalGenerator
{
    /// <summary>Attribute source added to consuming compilations.</summary>
    private const string AttributeSource = """
// <auto-generated />
using System;

namespace MitsubishiRx;

[AttributeUsage(AttributeTargets.Assembly | AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
public sealed class MitsubishiTagClientSchemaAttribute : Attribute
{
    public MitsubishiTagClientSchemaAttribute(string schemaJson)
    {
        SchemaJson = schemaJson ?? throw new ArgumentNullException(nameof(schemaJson));
    }

    public string SchemaJson { get; }
}
""";

    /// <summary>Diagnostic reported when generation fails unexpectedly.</summary>
    private static readonly DiagnosticDescriptor GenerationFailureDiagnostic = new(
        id: "MRTXGEN001",
        title: "Failed to generate Mitsubishi tag client",
        messageFormat: "{0}",
        category: "MitsubishiRx.Generators",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    /// <summary>Diagnostic reported when tag names are duplicated.</summary>
    private static readonly DiagnosticDescriptor DuplicateTagDiagnostic = new(
        id: "MRTXGEN002",
        title: "Duplicate generated tag name",
        messageFormat: "Schema contains duplicate tag name '{0}'",
        category: "MitsubishiRx.Generators",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    /// <summary>Diagnostic reported when a group references a missing tag.</summary>
    private static readonly DiagnosticDescriptor UnknownGroupTagDiagnostic = new(
        id: "MRTXGEN003",
        title: "Unknown generated group tag reference",
        messageFormat: "Group '{0}' references unknown tag '{1}'",
        category: "MitsubishiRx.Generators",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    /// <summary>Diagnostic reported when a tag has an unsupported data type.</summary>
    private static readonly DiagnosticDescriptor UnsupportedDataTypeDiagnostic = new(
        id: "MRTXGEN004",
        title: "Unsupported generated tag data type",
        messageFormat: "Tag '{0}' uses unsupported data type '{1}'",
        category: "MitsubishiRx.Generators",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    /// <summary>Diagnostic reported when different schema names sanitize to the same identifier.</summary>
    private static readonly DiagnosticDescriptor SanitizedIdentifierCollisionDiagnostic = new(
        id: "MRTXGEN005",
        title: "Generated identifier collision",
        messageFormat: "Generated identifier '{0}' is produced by multiple {1}: {2}",
        category: "MitsubishiRx.Generators",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    /// <summary>Diagnostic reported when a tag has no name.</summary>
    private static readonly DiagnosticDescriptor EmptyTagNameDiagnostic = new(
        id: "MRTXGEN006",
        title: "Empty generated tag name",
        messageFormat: "Tag name must not be empty",
        category: "MitsubishiRx.Generators",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    /// <summary>Diagnostic reported when a group has no name.</summary>
    private static readonly DiagnosticDescriptor EmptyGroupNameDiagnostic = new(
        id: "MRTXGEN007",
        title: "Empty generated group name",
        messageFormat: "Group name must not be empty",
        category: "MitsubishiRx.Generators",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    /// <summary>Diagnostic reported when a group has no tag members.</summary>
    private static readonly DiagnosticDescriptor EmptyGroupMembershipDiagnostic = new(
        id: "MRTXGEN008",
        title: "Empty generated group membership",
        messageFormat: "Group '{0}' must reference at least one tag",
        category: "MitsubishiRx.Generators",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    /// <summary>Diagnostic reported when group names are duplicated.</summary>
    private static readonly DiagnosticDescriptor DuplicateGroupDiagnostic = new(
        id: "MRTXGEN009",
        title: "Duplicate generated group name",
        messageFormat: "Schema contains duplicate group name '{0}'",
        category: "MitsubishiRx.Generators",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    /// <summary>Diagnostic reported when a group contains an empty tag reference.</summary>
    private static readonly DiagnosticDescriptor EmptyGroupTagReferenceDiagnostic = new(
        id: "MRTXGEN010",
        title: "Empty generated group tag reference",
        messageFormat: "Group '{0}' contains an empty tag reference",
        category: "MitsubishiRx.Generators",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    /// <summary>Diagnostic reported when a group references the same tag more than once.</summary>
    private static readonly DiagnosticDescriptor DuplicateGroupTagReferenceDiagnostic = new(
        id: "MRTXGEN011",
        title: "Duplicate generated group tag reference",
        messageFormat: "Group '{0}' references tag '{1}' more than once",
        category: "MitsubishiRx.Generators",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    /// <summary>Supported schema data types.</summary>
    private static readonly HashSet<string> SupportedDataTypes = new(StringComparer.OrdinalIgnoreCase)
    {
        "Bit",
        "Word",
        "DWord",
        "Float",
        "String",
        "Int16",
        "UInt16",
        "Int32",
        "UInt32",
    };

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static productionContext =>
            productionContext.AddSource(
                "MitsubishiTagClientSchemaAttribute.g.cs",
                SourceText.From(AttributeSource, Encoding.UTF8)));

        var schemaValues = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) => node is AttributeSyntax attribute && MightBeSchemaAttribute(attribute),
                transform: static (syntaxContext, _) => ExtractSchemaLiteral(syntaxContext))
            .Where(static schema => !string.IsNullOrWhiteSpace(schema))
            .Collect();

        context.RegisterSourceOutput(schemaValues, static (productionContext, schemas) =>
        {
            if (schemas.IsDefaultOrEmpty)
            {
                return;
            }

            try
            {
                var model = SchemaModel.Parse(schemas[0]!);
                if (!ValidateModel(model, productionContext))
                {
                    return;
                }

                var source = MitsubishiTagClientEmitter.Emit(model);
                productionContext.AddSource("MitsubishiTagClient.g.cs", SourceText.From(source, Encoding.UTF8));
            }
            catch (Exception ex)
            {
                productionContext.ReportDiagnostic(Diagnostic.Create(
                    GenerationFailureDiagnostic,
                    Location.None,
                    ex.Message));
            }
        });
    }

    /// <summary>Validates a parsed schema model.</summary>
    /// <param name="model">Parsed schema model.</param>
    /// <param name="context">Source production context.</param>
    /// <returns><c>true</c> when the model is valid.</returns>
    private static bool ValidateModel(SchemaModel model, SourceProductionContext context)
    {
        var isValid = true;
        var sanitizedTagNames = new Dictionary<string, List<string>>(StringComparer.Ordinal);
        var sanitizedGroupNames = new Dictionary<string, List<string>>(StringComparer.Ordinal);

        isValid &= ValidateTags(model.Tags, context, sanitizedTagNames);

        var knownTags = new HashSet<string>(model.Tags.Where(static tag => !string.IsNullOrWhiteSpace(tag.Name)).Select(static tag => tag.Name), StringComparer.OrdinalIgnoreCase);
        isValid &= ValidateGroups(model.Groups, knownTags, context, sanitizedGroupNames);

        ReportSanitizedCollisions(context, sanitizedTagNames, "tag names", ref isValid);
        ReportSanitizedCollisions(context, sanitizedGroupNames, "group names", ref isValid);

        return isValid;
    }

    /// <summary>Validates tag entries.</summary>
    /// <param name="tags">Tag entries.</param>
    /// <param name="context">Source production context.</param>
    /// <param name="sanitizedTagNames">Sanitized tag name index.</param>
    /// <returns><c>true</c> when all tags are valid.</returns>
    private static bool ValidateTags(IReadOnlyList<TagModel> tags, SourceProductionContext context, Dictionary<string, List<string>> sanitizedTagNames)
    {
        var isValid = true;
        var seenTags = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        foreach (var tag in tags)
        {
            isValid &= ValidateTag(tag, context, seenTags, sanitizedTagNames);
        }

        return isValid;
    }

    /// <summary>Validates one tag entry.</summary>
    /// <param name="tag">Tag entry.</param>
    /// <param name="context">Source production context.</param>
    /// <param name="seenTags">Observed tag names.</param>
    /// <param name="sanitizedTagNames">Sanitized tag name index.</param>
    /// <returns><c>true</c> when the tag is valid.</returns>
    private static bool ValidateTag(TagModel tag, SourceProductionContext context, HashSet<string> seenTags, Dictionary<string, List<string>> sanitizedTagNames)
    {
        if (string.IsNullOrWhiteSpace(tag.Name))
        {
            context.ReportDiagnostic(Diagnostic.Create(EmptyTagNameDiagnostic, Location.None));
            return false;
        }

        var isValid = true;
        if (!seenTags.Add(tag.Name))
        {
            context.ReportDiagnostic(Diagnostic.Create(DuplicateTagDiagnostic, Location.None, tag.Name));
            isValid = false;
        }

        if (!string.IsNullOrWhiteSpace(tag.DataType) && !SupportedDataTypes.Contains(tag.DataType!))
        {
            context.ReportDiagnostic(Diagnostic.Create(UnsupportedDataTypeDiagnostic, Location.None, tag.Name, tag.DataType));
            isValid = false;
        }

        AddSanitizedName(sanitizedTagNames, MitsubishiTagClientEmitter.SanitizeIdentifier(tag.Name), tag.Name);
        return isValid;
    }

    /// <summary>Validates group entries.</summary>
    /// <param name="groups">Group entries.</param>
    /// <param name="knownTags">Known tag names.</param>
    /// <param name="context">Source production context.</param>
    /// <param name="sanitizedGroupNames">Sanitized group name index.</param>
    /// <returns><c>true</c> when all groups are valid.</returns>
    private static bool ValidateGroups(
        IReadOnlyList<GroupModel> groups,
        HashSet<string> knownTags,
        SourceProductionContext context,
        Dictionary<string, List<string>> sanitizedGroupNames)
    {
        var isValid = true;
        var seenGroups = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        foreach (var group in groups)
        {
            isValid &= ValidateGroup(group, knownTags, context, seenGroups, sanitizedGroupNames);
        }

        return isValid;
    }

    /// <summary>Validates one group entry.</summary>
    /// <param name="group">Group entry.</param>
    /// <param name="knownTags">Known tag names.</param>
    /// <param name="context">Source production context.</param>
    /// <param name="seenGroups">Observed group names.</param>
    /// <param name="sanitizedGroupNames">Sanitized group name index.</param>
    /// <returns><c>true</c> when the group is valid.</returns>
    private static bool ValidateGroup(
        GroupModel group,
        HashSet<string> knownTags,
        SourceProductionContext context,
        HashSet<string> seenGroups,
        Dictionary<string, List<string>> sanitizedGroupNames)
    {
        var isValid = ValidateGroupName(group, context, seenGroups, sanitizedGroupNames);

        if (group.TagNames.Count == 0)
        {
            context.ReportDiagnostic(Diagnostic.Create(EmptyGroupMembershipDiagnostic, Location.None, group.Name));
            isValid = false;
        }

        isValid &= ValidateGroupTagReferences(group, knownTags, context);
        return isValid;
    }

    /// <summary>Validates one group name.</summary>
    /// <param name="group">Group entry.</param>
    /// <param name="context">Source production context.</param>
    /// <param name="seenGroups">Observed group names.</param>
    /// <param name="sanitizedGroupNames">Sanitized group name index.</param>
    /// <returns><c>true</c> when the group name is valid.</returns>
    private static bool ValidateGroupName(
        GroupModel group,
        SourceProductionContext context,
        HashSet<string> seenGroups,
        Dictionary<string, List<string>> sanitizedGroupNames)
    {
        if (string.IsNullOrWhiteSpace(group.Name))
        {
            context.ReportDiagnostic(Diagnostic.Create(EmptyGroupNameDiagnostic, Location.None));
            return false;
        }

        var isValid = true;
        if (!seenGroups.Add(group.Name))
        {
            context.ReportDiagnostic(Diagnostic.Create(DuplicateGroupDiagnostic, Location.None, group.Name));
            isValid = false;
        }

        AddSanitizedName(sanitizedGroupNames, MitsubishiTagClientEmitter.SanitizeIdentifier(group.Name), group.Name);
        return isValid;
    }

    /// <summary>Validates all tag references for one group.</summary>
    /// <param name="group">Group entry.</param>
    /// <param name="knownTags">Known tag names.</param>
    /// <param name="context">Source production context.</param>
    /// <returns><c>true</c> when all references are valid.</returns>
    private static bool ValidateGroupTagReferences(GroupModel group, HashSet<string> knownTags, SourceProductionContext context)
    {
        var isValid = true;
        var seenGroupTagNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        foreach (var tagName in group.TagNames)
        {
            isValid &= ValidateGroupTagReference(group.Name, tagName, knownTags, seenGroupTagNames, context);
        }

        return isValid;
    }

    /// <summary>Validates one group tag reference.</summary>
    /// <param name="groupName">Group name.</param>
    /// <param name="tagName">Referenced tag name.</param>
    /// <param name="knownTags">Known tag names.</param>
    /// <param name="seenGroupTagNames">Observed tag references for this group.</param>
    /// <param name="context">Source production context.</param>
    /// <returns><c>true</c> when the reference is valid.</returns>
    private static bool ValidateGroupTagReference(
        string groupName,
        string tagName,
        HashSet<string> knownTags,
        HashSet<string> seenGroupTagNames,
        SourceProductionContext context)
    {
        if (string.IsNullOrWhiteSpace(tagName))
        {
            context.ReportDiagnostic(Diagnostic.Create(EmptyGroupTagReferenceDiagnostic, Location.None, groupName));
            return false;
        }

        if (!seenGroupTagNames.Add(tagName))
        {
            context.ReportDiagnostic(Diagnostic.Create(DuplicateGroupTagReferenceDiagnostic, Location.None, groupName, tagName));
            return false;
        }

        if (knownTags.Contains(tagName))
        {
            return true;
        }

        context.ReportDiagnostic(Diagnostic.Create(UnknownGroupTagDiagnostic, Location.None, groupName, tagName));
        return false;
    }

    /// <summary>Adds an original name to the sanitized identifier index.</summary>
    /// <param name="index">Sanitized identifier index.</param>
    /// <param name="sanitizedName">Sanitized identifier.</param>
    /// <param name="originalName">Original schema name.</param>
    private static void AddSanitizedName(Dictionary<string, List<string>> index, string sanitizedName, string originalName)
    {
        if (!index.TryGetValue(sanitizedName, out var originals))
        {
            originals = [];
            index[sanitizedName] = originals;
        }

        originals.Add(originalName);
    }

    /// <summary>Reports generated identifier collisions.</summary>
    /// <param name="context">Source production context.</param>
    /// <param name="index">Sanitized identifier index.</param>
    /// <param name="entityKind">Entity kind for diagnostics.</param>
    /// <param name="isValid">Current validation result.</param>
    private static void ReportSanitizedCollisions(SourceProductionContext context, Dictionary<string, List<string>> index, string entityKind, ref bool isValid)
    {
        foreach (var pair in index)
        {
            var distinctOriginals = pair.Value.Distinct(StringComparer.OrdinalIgnoreCase).ToArray();
            if (distinctOriginals.Length <= 1)
            {
                continue;
            }

            context.ReportDiagnostic(Diagnostic.Create(
                SanitizedIdentifierCollisionDiagnostic,
                Location.None,
                pair.Key,
                entityKind,
                string.Join(", ", distinctOriginals)));
            isValid = false;
        }
    }

    /// <summary>Returns whether the attribute syntax may be the generator schema attribute.</summary>
    /// <param name="attribute">Attribute syntax.</param>
    /// <returns><c>true</c> when the attribute may be the schema attribute.</returns>
    private static bool MightBeSchemaAttribute(AttributeSyntax attribute)
    {
        var name = attribute.Name.ToString();
        return name.Contains("MitsubishiTagClientSchema", StringComparison.Ordinal);
    }

    /// <summary>Extracts the schema JSON literal from a schema attribute.</summary>
    /// <param name="syntaxContext">Generator syntax context.</param>
    /// <returns>Schema JSON when one can be read.</returns>
    private static string? ExtractSchemaLiteral(GeneratorSyntaxContext syntaxContext)
    {
        if (syntaxContext.Node is not AttributeSyntax attribute || attribute.ArgumentList is null || attribute.ArgumentList.Arguments.Count == 0)
        {
            return null;
        }

        var expression = attribute.ArgumentList.Arguments[0].Expression;
        var constant = syntaxContext.SemanticModel.GetConstantValue(expression);
        if (constant.HasValue && constant.Value is string text)
        {
            return text;
        }

        return expression is LiteralExpressionSyntax literal ? literal.Token.ValueText : null;
    }

    /// <summary>Parsed generator schema.</summary>
    internal sealed class SchemaModel
    {
        /// <summary>Initializes a new instance of the <see cref="SchemaModel"/> class.</summary>
        /// <param name="tags">Parsed tags.</param>
        /// <param name="groups">Parsed groups.</param>
        private SchemaModel(IReadOnlyList<TagModel> tags, IReadOnlyList<GroupModel> groups)
        {
            Tags = tags;
            Groups = groups;
        }

        /// <summary>Gets the parsed tags.</summary>
        public IReadOnlyList<TagModel> Tags { get; }

        /// <summary>Gets the parsed groups.</summary>
        public IReadOnlyList<GroupModel> Groups { get; }

        /// <summary>Parses schema JSON.</summary>
        /// <param name="json">Schema JSON.</param>
        /// <returns>Parsed schema model.</returns>
        public static SchemaModel Parse(string json)
        {
            using var document = JsonDocument.Parse(json);
            var root = document.RootElement;

            var tags = ParseTags(root);
            var groups = ParseGroups(root);

            return new SchemaModel(tags, groups);
        }

        /// <summary>Parses tag entries from the schema root.</summary>
        /// <param name="root">Schema root element.</param>
        /// <returns>Parsed tag entries.</returns>
        private static List<TagModel> ParseTags(JsonElement root)
        {
            var tags = new List<TagModel>();
            if (!TryGetArray(root, "tags", out var tagsElement))
            {
                return tags;
            }

            foreach (var tag in tagsElement.EnumerateArray())
            {
                tags.Add(new TagModel(
                    name: GetStringProperty(tag, "name") ?? string.Empty,
                    dataType: GetStringProperty(tag, "dataType")));
            }

            return tags;
        }

        /// <summary>Parses group entries from the schema root.</summary>
        /// <param name="root">Schema root element.</param>
        /// <returns>Parsed group entries.</returns>
        private static List<GroupModel> ParseGroups(JsonElement root)
        {
            var groups = new List<GroupModel>();
            if (!TryGetArray(root, "groups", out var groupsElement))
            {
                return groups;
            }

            foreach (var group in groupsElement.EnumerateArray())
            {
                groups.Add(new GroupModel(
                    name: GetStringProperty(group, "name") ?? string.Empty,
                    tagNames: ParseTagNames(group)));
            }

            return groups;
        }

        /// <summary>Parses tag names from a group entry.</summary>
        /// <param name="group">Group element.</param>
        /// <returns>Parsed tag names.</returns>
        private static List<string> ParseTagNames(JsonElement group)
        {
            var tagNames = new List<string>();
            if (!TryGetArray(group, "tagNames", out var tagNamesElement))
            {
                return tagNames;
            }

            foreach (var tagName in tagNamesElement.EnumerateArray())
            {
                tagNames.Add(tagName.GetString() ?? string.Empty);
            }

            return tagNames;
        }

        /// <summary>Gets a string property value from an element.</summary>
        /// <param name="element">Source element.</param>
        /// <param name="propertyName">Property name.</param>
        /// <returns>Property value when present.</returns>
        private static string? GetStringProperty(JsonElement element, string propertyName)
            => element.TryGetProperty(propertyName, out var value) ? value.GetString() : null;

        /// <summary>Gets an array property value from an element.</summary>
        /// <param name="element">Source element.</param>
        /// <param name="propertyName">Property name.</param>
        /// <param name="value">Array value when present.</param>
        /// <returns><c>true</c> when the property is an array.</returns>
        private static bool TryGetArray(JsonElement element, string propertyName, out JsonElement value)
        {
            if (element.TryGetProperty(propertyName, out value) && value.ValueKind == JsonValueKind.Array)
            {
                return true;
            }

            value = default;
            return false;
        }
    }

    /// <summary>Parsed tag schema entry.</summary>
    internal sealed class TagModel
    {
        /// <summary>Initializes a new instance of the <see cref="TagModel"/> class.</summary>
        /// <param name="name">Tag name.</param>
        /// <param name="dataType">Tag data type.</param>
        public TagModel(string name, string? dataType)
        {
            Name = name;
            DataType = dataType;
        }

        /// <summary>Gets the tag name.</summary>
        public string Name { get; }

        /// <summary>Gets the tag data type.</summary>
        public string? DataType { get; }
    }

    /// <summary>Parsed group schema entry.</summary>
    internal sealed class GroupModel
    {
        /// <summary>Initializes a new instance of the <see cref="GroupModel"/> class.</summary>
        /// <param name="name">Group name.</param>
        /// <param name="tagNames">Names of tags in the group.</param>
        public GroupModel(string name, IReadOnlyList<string> tagNames)
        {
            Name = name;
            TagNames = tagNames;
        }

        /// <summary>Gets the group name.</summary>
        public string Name { get; }

        /// <summary>Gets the group tag names.</summary>
        public IReadOnlyList<string> TagNames { get; }
    }
}
